all: 1 2 3 4 5

1:
	gcc -o 1.ex teste1.c -L../lib/ -lsthread -Wall

2:
	gcc -o 2.ex teste2.c -L../lib/ -lsthread -Wall

3:
	gcc -o 3.ex teste3.c -L../lib/ -lsthread -Wall

4:
	gcc -o 4.ex teste4.c -L../lib/ -lsthread -Wall

5:
	gcc -o 5.ex teste5.c -L../lib/ -lsthread -Wall

clean:
	rm *.ex
